name: release
on:
  push:
    tags:
      - 'v*'
env:
  tag: ${GITHUB_REF#refs/tags/v}
  prerelease: ${{ contains(github.ref, '-') }}
jobs:
  release-github:
    name: Release on GitHub
    runs-on: ubuntu-20.04
    container:
      image: quay.io/cybozu/golang:1.16-focal
    steps:
      - uses: actions/checkout@v2
      - name: Prepare files
        run: |
          curl -sLf https://github.com/cybozu-go/cke/releases/download/v1.19.3/sonobuoy.tar.gz -O
          mkdir /tmp/upload
          cp ./sonobuoy.tar.gz /tmp/upload
          tar xzf ./sonobuoy.tar.gz -C /tmp/upload --strip-components=4 plugins/e2e/results/global/e2e.log plugins/e2e/results/global/junit_01.xml
      - run: echo ${{ env.tag }}
      - name: Create release
        run: |
          OWNER=$(echo ${{ github.repository }} | cut -d '/' -f 1)
          REPOSITORY=$(echo ${{ github.repository }} | cut -d '/' -f 2)
          if ${{ env.prerelease }}; then
            PRERELEASE="-prerelease"
          fi
          ghr -t ${{ secrets.GITHUB_TOKEN }} -u ${OWNER} -r ${REPOSITORY} -n v${{ env.tag }} ${PRERELEASE} -b "See [CHANGELOG.md](./CHANGELOG.md) for details." v${{ env.tag }} /tmp/upload/
